version: '3.4'

services:

  sensor:
    build:
      dockerfile: Dockerfile
      context: ./sensor
    container_name: sensor
    networks:
      - pfm
    depends_on:
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto:1.6.12
    container_name: mosquitto
    ports:
      - "1883:1883"
    networks:
      - pfm
  nifi:
    image: apache/nifi
    container_name: nifi
    ports: 
      - "8080:8080"
    networks:
      - pfm
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - pfm
    environment:
      - node.name=elasticsearch1
      - cluster.name=docker-cluster
      - discovery.seed_hosts=elasticsearch2
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      - bootstrap.memory_lock=true
      - xpack.watcher.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch2
    networks:
      - pfm
    environment:
      - node.name=elasticsearch2
      - cluster.name=docker-cluster
      - discovery.seed_hosts=elasticsearch1
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    ports:
     - "5601:5601"
    networks:
      - pfm
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch1:9200
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=min32bytelongstrongencryptionkey

networks:
  pfm:
    external: false
